import './globals.css'
import type { Metadata } from 'next'
import { Nunito as FontSans } from 'next/font/google'
import { cn } from '@/shared/ui/utils'
import { ThemeProvider, SocketProvider, AuthProvider } from './providers'
import { QueryClientProvider } from '@tanstack/react-query'
import { queryClient } from '@/shared/api/query-client'
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'
import Script from 'next/script'
import { ReactScan } from '@/shared/ui/react-scan'
import { Toaster } from '@/shared/ui'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const fontSans = FontSans({
  subsets: ['latin'],
  weight: ['400', '500', '700', '800', '900'],
  variable: '--font-sans',
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <Script src="https://unpkg.com/react-scan/dist/auto.global.js" />
      </head>
      <ReactScan />
      <body
        suppressHydrationWarning
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          fontSans.variable,
        )}>
        <QueryClientProvider client={queryClient}>
          <AuthProvider>
            <SocketProvider>
              <ThemeProvider>
                {children}
                <Toaster />
              </ThemeProvider>
              <ReactQueryDevtools initialIsOpen={false} />
            </SocketProvider>
          </AuthProvider>
        </QueryClientProvider>
      </body>
    </html>
  )
}
